PROCESS BEFORE OUTPUT.
  MODULE status_0100.

  CALL SUBSCREEN sub1 INCLUDING sy-repid '0110'.
  CALL SUBSCREEN sub2 INCLUDING sy-repid '0120'.
  CALL SUBSCREEN sub3 INCLUDING sy-repid '0130'.
  CALL SUBSCREEN sub4 INCLUDING sy-repid '0140'.
  CALL SUBSCREEN sub5 INCLUDING sy-repid '0150'.

PROCESS AFTER INPUT.

  CALL SUBSCREEN sub1.
  CALL SUBSCREEN sub2.
  CALL SUBSCREEN sub3.
  CALL SUBSCREEN sub4.
  CALL SUBSCREEN sub5.

  MODULE user_command_0100.
